[package]
name = "gecko-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gecko-lexer = { path = "../gecko-lexer" }
gecko-error = { path = "../gecko-error" }

